### ISSUE TITLE
US-1

### ISSUE THREAD

**Issue by Charlotte-Ketteler** [Charlotte-Ketteler/capstone-project#1]
## Value Proposition

**As a**  User
**I want to** see the time slots for the riding lessons. When the User clicks on a time slot, a form appears under the Button and they can choose how many students want zu participate and which horse they want to ride. 

​

## Description

![US-1](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/3b84aef0-d0d8-4c17-9def-37f2cb0af075)

## Acceptance Criteria

- [ ] The heading says "time slots". 
- [ ] There is a button for each time slot.
- [ ] By clicking on one button a form appears under the clicked button.
- [ ] The Form shows a select box for the number of participants.
- [ ] The Form shows a select box for the available horses.
- [ ] The Form shows a booking button.
- [ ] There are three icons in the footer: The house icon leads you to homepage, the calendar icon leads you to booking slots, the horse shoe icon leads you to all booked appointments overview. 
      ​
## Tasks

- [ ] write component TimeSlotsButtons
- [ ] write form with select box for participants and horses
- [ ] write booking buttons
- [ ] link icons Home and Horseshoe to landing page
      ​

## Complexity

XL

**Comment by donacrisante** [comment]
I would take care of the footer in a extra US. In the first US I would just create the form. I would implement the footer, when you have created the other pages. It was not recommended to link pages that lead to empty pages. Do you remember?

**Comment by Charlotte-Ketteler** [comment]
Okay, thank's for your help. I will change this. :)
