### ISSUE TITLE
US5-Home

### ISSUE THREAD

**Issue by Charlotte-Ketteler** [Charlotte-Ketteler/capstone-project#10]
## Value Proposition

**As an** Admin
**I want to** be greeted on the homepage. 
​

## Description

![US-5 home page](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/29801c6a-3654-491d-9096-7207f05b5546)

​

## Acceptance Criteria

- [ ] There is a text, that greets the admin.
- [ ] There is a picture with a cowgirl to make page look more pleasant. ​
## Tasks

- [ ] Create component Homepage and implement Text and picture.
- [ ] import component Homepage in index.js
- [ ] style picture and text. 
      ​

## Complexity

S
