### ISSUE TITLE
US6- Style BookingPage

### ISSUE THREAD

**Issue by Charlotte-Ketteler** [Charlotte-Ketteler/capstone-project#11]
## Value Proposition

**As an** admin 
**I want to** have a pleasant design for a good UX.

​

## Description

![US-6 BookingPage](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/13bddcbd-d2c4-4a82-a360-0680fab9d903)

## Acceptance Criteria

- [ ] The timeslots buttons have the color  #ABDBE3
- [ ] There is a button for "gebuchte Plätze:"
- [ ] There is a button for "Buchung hinzufügen"
- [ ] The "löschen" button has the color #ABDBE3
- [ ] The Header Typo is styled

## Tasks

- [ ] change color of timeslots button to #ABDBE3
- [ ] create button for "gebuchte Plätze:"
- [ ] style button for "gebuchte Plätze:"
- [ ] create button for "Buchung hinzufügen"
- [ ] style button for "Buchung hinzufügen"
- [ ] style "löschen" button
- [ ] style H1 in Header Component
      ​

## Complexity

M

**Comment by alexander-bick** [comment]
Looks like a very pleasant design and UX and makes all sense to me 👌🏼🙂

**Comment by alexander-bick** [comment]
The new design looks even better to me and has a more modern touch 👍🙂 One thing you might consider is to center the content of your homepage.
