### ISSUE TITLE
US7-StyleCard

### ISSUE THREAD

**Issue by Charlotte-Ketteler** [Charlotte-Ketteler/capstone-project#14]
## Value Proposition

**As an** ...admin
**I want to** ... have a nice looking booking card
**so that** ... I have a good overview over the details.
​

## Description

![US-7 StyleCard](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/cf16cf4b-6c88-4630-86ca-a546618f8587)

​

## Acceptance Criteria

- [ ] There is a booking card with booked appointment.
- [ ] There is a purple delete button.

## Tasks

- [ ] style grey background for Uhrzeit, Personen and Pferde
- [ ] implement line between Uhrzeit, Personen and Pferde
- [ ] style delete button and move under booking information
      
## Complexity

S

**Comment by alexander-bick** [comment]
Looks like really nice further improvement of your design 👍🏼
