### ISSUE TITLE
US-8 ToDo List

### ISSUE THREAD

**Issue by Charlotte-Ketteler** [Charlotte-Ketteler/capstone-project#16]
## Value Proposition

**As an** Admin
**I want a** ToDo List
**so that** I have an overview of all my tasks.
​

## Description
​
![US-8 ToDo](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/f343549d-f61a-4f5b-b897-06244bf5a37e)

## Acceptance Criteria

- [ ] An Input Field is displayed with an add button.
- [ ] When a task added, the task and delete button are displayed on greyish Background. 
- [ ] An icon is implemented in Footer for ToDo List

## Tasks

- [ ] Write ToDo function with useLocalStorageState.
- [ ] Wirte function to add ToDo.
- [ ] Wirte function to delete ToDo.
- [ ] Style ToDo List 
- [ ] Implement ToDo Icon in Footer. 
      ​

## Complexity

M

**Comment by MiketheBite** [comment]
Sounds like a good idea! But do it simple, we are running out of time 😅
