### ISSUE TITLE
US3 - Booked Appointments

### ISSUE THREAD

**Issue by Charlotte-Ketteler** [Charlotte-Ketteler/capstone-project#3]
## Value Proposition

**As a**  User 
**I want to**  to see my booked appointments
**so that** I have an overview. I can also change or delete the appointments. 
​

## Description
![US-3 appointment overview](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/b015f45f-6a66-4405-af79-59629397c7d6)
​

## Acceptance Criteria

- [ ] The heading says "Terminübersicht"
- [ ] There are cards with booked appointments and the details of each appointment.
- [ ] There is a "delete" button.
- [ ] There is a "change appointment" button. 
      ​

## Tasks

- [ ] Create AppointmentsOverview component which contains cards with detail of appointments.
- [ ] Create "delete" and "change" Buttons.
      ​

## Complexity

L

**Comment by MiketheBite** [comment]
Looks great to me!! ;)
