### ISSUE TITLE
US4 - Change Appointment

### ISSUE THREAD

**Issue by Charlotte-Ketteler** [Charlotte-Ketteler/capstone-project#7]
## Value Proposition

**As a** User
**I want to** be able  to change the appointment. 
​

## Description
​
![US-4 change appointment](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/13e3999e-fb3b-482d-91d4-2e09dec48b71)

![US-4 change appointment_2v2](https://github.com/Charlotte-Ketteler/capstone-project/assets/127936697/fae5808c-844b-47a5-8a85-552c430481ab)

## Acceptance Criteria

- [ ] There is a form where User can change the appointment.
- [ ] There is a "ändern" Button, to commit changes.

## Tasks

- [ ] Create form that is connected with BookingOverview.
- [ ] create "ändern" Button that leads to SuccessfullyChangedPage
- [ ] write three tests for components

## Complexity

XL

**Comment by florianblaschke** [comment]
LGTM, just remove the boxes under your tasks and criteria.
